apiVersion: v1
kind: BuildConfig
metadata:
  name: flowerpipeline
  namespace: 
  labels:
    name: flowerpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/masauve/pipeline'
      ref: master
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkinsfile
  output:
  resources:
  postCommit:
